-ifndef(textDefine_SkillFixInfo_FR_hrl).
-define(textDefine_SkillFixInfo_FR_hrl, 1).
-define(SCN213, "Destin Inversé").
-define(SCD213, "Lorsque vous utilisez des reliques pour attaquer, il y a {0}% de chance de déclencher Destin Inversé et d'infliger {1}% de DGT avec 100% d'effet de sangsue.TdR : {2} sec").
-define(SCN41001, "Améliorer Compétence").
-define(SCD40001, "Augmente les dégâts fixes de la compétence {0}").
-define(SCN51001, "Ascension de Compétence Temporaire").
-define(SCD51001, "Multiplicateur des DGT de Compétence augmente à +{0}%").
-define(BCN1021, "Puissance du Dieu de la Guerre Renforcée").
-define(BCN1031, "Garde de Thor Renforcée").
-define(BCN2011, "Esprit de Vulcain Renforcé").
-define(BCN2021, "Esprit de Khione Renforcé").
-define(BCN3021, "Force de la Nature Renforcé").
-define(BCN3031, "Puissance de Foudre Renforcée").
-define(BCD1021, "Durée de Puissance du Dieu de la Guerre +{0} sec").
-define(BCD1031, "Durée de Garde de Thor +{0} sec").
-define(BCD2011, "Durée d'Esprit de Vulcain +{0} sec").
-define(BCD2021, "Durée d'Esprit de Khione +{0} sec").
-define(BCD3021, "Durée de Force de la Nature +{0} sec").
-define(BCD3031, "Durée de Puissance de Foudre +{0} sec").
-define(BCN1001, "Amélioration de Colère").
-define(BCD1001, "Colère donne +{0}% de Bonus d'ATQ.Rugissement donne +{1}% de Taux Crit.").
-define(BCN2001, "Imbue de Magie").
-define(BCD2001, "Toutes les durées de Pouvoir +{0} sec.").
-define(BCN3001, "Amélioration de Bataille").
-define(BCD3001, "Chaque pile de Focalisation donne +{0}% de DGT Bonus.Chaque pile de Tonnerre donne +{1}% de Réduction de DGT.").
-define(SCN30001, "Avatar de la Sagesse : Ascension effectuée").
-define(SCN30011, "Juge Victorieux : Ascension effectuée").
-define(SCN30021, "Lance Tourbillonnante : Ascension effectuée").
-define(SCN30031, "Bouclier des Soupirs : Ascension effectuée").
-define(SCN30041, "Poussée de Lance : Ascension effectuée").
-define(SCN30051, "Lance Divine : Ascension effectuée").
-define(SCN30101, "Sceau de Vengeance : Ascension effectuée").
-define(SCN30111, "Appel du Corbeau : Ascension effectuée").
-define(SCN30121, "Siphon d'Énergie : Ascension effectuée").
-define(SCN30131, "Rites du Corbeau : Ascension effectuée").
-define(SCN30141, "Danse du Corbeau : Ascension effectuée").
-define(SCN30151, "Tourbillon de Vengeance : Ascension effectuée").
-define(SCN30201, "Domination de Thor : Ascension effectuée").
-define(SCN30211, "Foudre : Ascension effectuée").
-define(SCN30221, "Craquement de Tonnerre : Ascension effectuée").
-define(SCN30231, "Souffle de Foudre : Ascension effectuée").
-define(SCN30241, "Tonnerre Assourdissant : Ascension effectuée").
-define(SCN30251, "Marteau de Thor : Ascension effectuée").
-define(SCN30301, "Gardien du Pharaon : Ascension effectuée").
-define(SCN30311, "Corona : Ascension effectuée").
-define(SCN30321, "Halo Solaire : Ascension effectuée").
-define(SCN30331, "Disque Solaire : Ascension effectuée").
-define(SCN30341, "Ancienne Malédiction : Ascension effectuée").
-define(SCN30351, "Vent Solaire : Ascension effectuée").
-define(SCN30901, "").
-define(SCN31001, "").
-define(SCN31101, "").
-define(SCD30001, "DGT de Base Infligés +{0}%").
-define(SCD30011, "DGT de Base Infligés +{0}%").
-define(SCD30021, "DGT de Base Infligés +{0}%").
-define(SCD30031, "DGT de Base Infligés +{0}%").
-define(SCD30041, "DGT de Base Infligés +{0}%").
-define(SCD30051, "DGT de Base Infligés +{0}%").
-define(SCD30101, "DGT de Base Infligés +{0}%").
-define(SCD30111, "DGT de Base Infligés +{0}%").
-define(SCD30121, "DGT de Base Infligés +{0}%").
-define(SCD30131, "DGT de Base Infligés +{0}%").
-define(SCD30141, "DGT de Base Infligés +{0}%").
-define(SCD30151, "DGT de Base Infligés +{0}%").
-define(SCD30201, "DGT de Base Infligés +{0}%").
-define(SCD30211, "DGT de Base Infligés +{0}%").
-define(SCD30221, "DGT de Base Infligés +{0}%").
-define(SCD30231, "DGT de Base Infligés +{0}%").
-define(SCD30241, "DGT de Base Infligés +{0}%").
-define(SCD30251, "DGT de Base Infligés +{0}%").
-define(SCD30301, "DGT de Base Infligés +{0}%").
-define(SCD30311, "DGT de Base Infligés +{0}%").
-define(SCD30321, "DGT de Base Infligés +{0}%").
-define(SCD30331, "DGT de Base Infligés +{0}%").
-define(SCD30341, "DGT de Base Infligés +{0}%").
-define(SCD30351, "DGT de Base Infligés +{0}%").
-define(SCD61001, "Quand la Colère est active, le multiplicateur de DGT des compétences est de +{0}%").
-define(SCD61011, "La Puissance du Dieu de la Guerre fournit {0}% de Taux Crit supplémentaires").
-define(SCD61021, "La Garde de Thor fournit {0}% de Réduction de Blocage Supplémentaire").
-define(SCD62001, "Le Multiplicateur de DGT de compétence fourni par chaque pouvoir +{0}%").
-define(SCD62011, "Le Multiplicateur de Restauration de compétence fourni par chaque pouvoir +{0}%").
-define(SCD62021, "Lancer un compétence confère {0}% de chance d'accorder Pouvoir - Tempête de Feu (Bonus de DGT de Compétence +{1}%)").
-define(SCD62041, "Lancer un compétence confère {0}% de chance d'accorder Pouvoir - Tempête de Feu (Bonus de DGT de Compétence +{1]%)").
-define(SCD63001, "Possède {0}% de chance d'obtenir 2 couches de Focalisation").
-define(SCD63011, "Possède {0}% de chance d'obtenir 2 couches de Tonnerre").
-define(SCD63021, "Augmentation du multiplicateur de DGT des compétences de chaque pile de Focalisation +{0}%").
-define(SCD63031, "Augmentation du multiplicateur de DGT des compétences de chaque pile de Tonnerre +{0}%").
-define(BCD1041, "Durée de la Colère +{0} sec").
-define(BCD1051, "Durée de Rugissement +{0} sec").
-define(BCD1061, "Quand le Rugissement est actif, augmente les chances d'infliger Étourdissement de {0}%").
-define(BCD1071, "Durée de la Gardien +{0} sec").
-define(BCD1081, "Durée de la Saigner +{0} sec").
-define(BCD2031, "Lorsque le statut de Feu du Cœur prend fin, il y a {0}% de chance d'ajouter le statut à nouveau").
-define(BCD2041, "Lorsque le statut de Glace Eldritch prend fin, il y a {0}% de chance d'ajouter le statut à nouveau").
-define(BCD3041, "Quand la Force de la Nature est active, confère 1 couche de Focalisation tous les {0} sec").
-define(BCD3051, "Quand la Puissance de Foudre est active, confère 1 couche de Tonnerre tous les {0} sec").
-define(SFI_UNITS103, "s").
-define(SCN117, "Tempête de Givre Renforcée").
-define(SCD117, "DGT de Base Infligés +{0}%").
-define(SCN118, "Cornet de glace Renforcé").
-define(SCD118, "DGT de Base Infligés +{0}%").
-define(SCD70001, "").
-define(SCD41001, "Augmente le Multiplicateur de DGT de Compétence Fixe de {0}% ; Augmente les DGT de Compétence Fixe de {1}").
-define(SCN80001, "Juge Victorieux : Éveillé").
-define(SCN80011, "Juge Victorieux : Éveillé").
-define(SCN80021, "Lance Tourbillonnante : Éveillé").
-define(SCN80031, "Bouclier des Soupirs : Éveillé").
-define(SCN80041, "Poussée de Lance : Éveillé").
-define(SCN80051, "Lance Divine : Éveillé").
-define(SCN80101, "Danse du Corbeau : Éveillé").
-define(SCN80111, "Appel du Corbeau : Éveillé").
-define(SCN80121, "Siphon d'Énergie : Éveillé").
-define(SCN80131, "Rites du Corbeau : Éveillé").
-define(SCN80141, "Danse du Corbeau : Éveillé").
-define(SCN80151, "Tourbillon de Vengeance : Éveillé").
-define(SCN80201, "").
-define(SCN80211, "Foudre : Éveillé").
-define(SCN80221, "Craquement de Tonnerre : Éveillé").
-define(SCN80231, "Souffle de Foudre : Éveillé").
-define(SCN80241, "Tonnerre Assourdissant : Éveillé").
-define(SCN80251, "Marteau de Thor : Éveillé").
-define(SCN80301, "").
-define(SCN80311, "Corona : Éveillé").
-define(SCN80321, "Halo Solaire : Éveillé").
-define(SCN80331, "Disque Solaire : Éveillé").
-define(SCN80341, "Ancienne Malédiction : Éveillé").
-define(SCN80351, "Vent Solaire : Éveillé").
-define(SCN80901, "").
-define(SCD80901, "").
-define(SCN81001, "").
-define(SCN81101, "").
-define(SCD81001, "").
-define(SCD80001, "Le dernier coup a {0}% de chance d'aveugler (Taux de Toucher -10%) et Placidité (Taux Crit -20%) l'ennemi pendant {1} sec.").
-define(SCD80011, "{0}% de chance d'infliger Brise-genou (Vitesse de Déplacement -33%) pendant {1} sec.").
-define(SCD80021, "Inflige {0}% de DÉF en tant que dégâts.").
-define(SCD80031, "{0}% de chance d'accorder aux coéquipiers un bouclier de {1}% d'ATQ.").
-define(SCD80041, "Inflige des dégâts supplémentaires équivalents à {0}% des PV max.").
-define(SCD80051, "{0}% de chance de supprimer 1 couche de débuff.").
-define(SCD80101, "En lançant cette compétence, récupère {0}% des PV max.").
-define(SCD80111, "{0}% de chance d'infliger Flétrissure à chaque fois que la compétence est lancée.").
-define(SCD80121, "Inflige Saignement à la cible, lui faisant perdre {0}% des PV.").
-define(SCD80131, "Inflige Saignement à la cible, lui faisant perdre {0}% des PV.").
-define(SCD80141, "{0}% de chance d'infliger Flétrissure à chaque fois que la compétence est lancée.").
-define(SCD80151, "Soigne toute l'équipe pour {0}% d'ATQ.").
-define(SCD80201, "Inflige des dégâts supplémentaires équivalents à {0}% des PV max.").
-define(SCD80211, "{0}% de chance de supprimer un buff des cibles proches.").
-define(SCD80221, "Inflige des dégâts supplémentaires équivalents à {0}% des PV max.").
-define(SCD80231, "{0}% de chance de supprimer 2 buffs des cibles proches.").
-define(SCD80241, "Inflige des dégâts supplémentaires équivalents à {0}% des PV max.").
-define(SCD80251, "Inflige des dégâts supplémentaires équivalents à {0}% des PV max.").
-define(SCD80301, "").
-define(SCD80311, "Chaque coup a {0}% de chance de déclencher Brûlure.").
-define(SCD80321, "{0}% de chance de déclencher Brûlure en plus 1 fois de plus.").
-define(SCD80331, "{0}% de chance de déclencher Brûlure en plus 2 fois de plus.").
-define(SCD80341, "{0}% de chance d'étourdir la cible pendant 1.5 sec.").
-define(SCD80351, "Chaque coup a {0}% de chance de déclencher Brûlure 1 fois de plus.").
-define(SCN70001, "Juge Victorieux : Renforcé(e)").
-define(SCN70011, "Juge Victorieux : Renforcé(e)").
-define(SCN70021, "Lance Tourbillonnante : Renforcé(e)").
-define(SCN70031, "Bouclier des Soupirs : Renforcé(e)").
-define(SCN70041, "Poussée de Lance : Renforcé(e)").
-define(SCN70051, "Lance Divine : Renforcé(e)").
-define(SCN70101, "Danse du Corbeau : Renforcé(e)").
-define(SCN70111, "Appel du Corbeau : Renforcé(e)").
-define(SCN70121, "Siphon d'Énergie : Renforcé(e)").
-define(SCN70131, "Rites du Corbeau : Renforcé(e)").
-define(SCN70141, "Danse du Corbeau : Renforcé(e)").
-define(SCN70151, "Tourbillon de Vengeance : Renforcé(e)").
-define(SCN70201, "").
-define(SCN70211, "Foudre : Renforcé(e)").
-define(SCN70221, "Craquement de Tonnerre : Renforcé(e)").
-define(SCN70231, "Souffle de Foudre : Renforcé(e)").
-define(SCN70241, "Tonnerre Assourdissant : Renforcé(e)").
-define(SCN70251, "Marteau de Thor : Renforcé(e)").
-define(SCN70301, "").
-define(SCN70311, "Corona : Renforcé(e)").
-define(SCN70321, "Halo Solaire : Renforcé(e)").
-define(SCN70331, "Disque Solaire : Renforcé(e)").
-define(SCN70341, "Ancienne Malédiction : Renforcé(e)").
-define(SCN70351, "Vent Solaire : Renforcé(e)").
-define(SCN70901, "").
-define(SCN71001, "").
-define(SCN71101, "").
-define(SCD61031, "Ignore {0}% de la DÉF des ennemis sous Saignement.").
-define(SCD62061, "Lorsque les PV sont supérieurs à {0}%, le multiplicateur des DGT des Compétences augmente à +{1}%.").
-define(SCD62071, "Chance d'infliger un effet de Gel +{0}%").
-define(SCD63061, "Pour chaque effet de Focalisation obtenu, augmente le multiplicateur de DGT des PV max de la cible de {0}%.").
-define(SCD63071, "Pour chaque effet de Tonnerre obtenu, augmente le Bonus de Compétence de {0}%.").
-define(SCD10001, "ATQ de Chariot +{0}%").
-define(SCN70401, "Roi Tartare : Renforcé(e)").
-define(SCN70411, "Flèche Spectrale : Renforcé(e)").
-define(SCN70421, "Loup Tartare : Renforcé(e)").
-define(SCN70431, "Impact Effrayant : Renforcé(e)").
-define(SCN70441, "Enchevêtrement Fantôme : Renforcé(e)").
-define(SCN70451, "Banshee Espace : Renforcé(e)").
-define(SCN70501, "Seigneur de la Guerre : Renforcé(e)").
-define(SCN70511, "Compétence de Récolte : Renforcé(e)").
-define(SCN70521, "Attaque au Sabre : Renforcé(e)").
-define(SCN70531, "Raid Tranchant : Renforcé(e)").
-define(SCN70541, "Étranglement du Sabre : Renforcé(e)").
-define(SCN70551, "Exécution Finale : Renforcé(e)").
-define(SCN80401, "Roi Tartare : Éveillé").
-define(SCN80411, "Flèche Spectrale : Éveillé").
-define(SCN80421, "Loup Tartare : Éveillé").
-define(SCN80431, "Impact Effrayant : Éveillé").
-define(SCN80441, "Enchevêtrement Fantôme : Éveillé").
-define(SCN80451, "Banshee Espace : Éveillé").
-define(SCN80501, "Seigneur de la Guerre : Éveillé").
-define(SCN80511, "Compétence de Récolte : Éveillé").
-define(SCN80521, "Attaque au Sabre : Éveillé").
-define(SCN80531, "Raid Tranchant : Éveillé").
-define(SCN80541, "Étranglement du Sabre : Éveillé").
-define(SCN80551, "Exécution Finale : Éveillé").
-define(SCD80401, "Les premiers DGT infligée provoque Fragilité (Réduction DGT de Compétence -15%) pendant {0} sec.").
-define(SCD80411, "Ignore {0}% de la DÉF de la cible.").
-define(SCD80421, "Soigne une fois de plus pour des PV égaux à {0}% de l'ATQ.").
-define(SCD80431, "Les premiers DGT infligés provoque un Adoucissement (Réduction de DGT de -10%) pendant {0} sec.").
-define(SCD80441, "Premier DGT infligé provoque Malédiction (Taux de Toucher -20%) pendant {0} sec.").
-define(SCD80451, "Le premier DGT infligé provoque Contamination (Bonus de Guérison -20%) pendant {0} sec.").
-define(SCD80501, "Possède {0}% de chance de supprimer une couche d'affaiblissement pour le lanceur de sorts après une transformation réussie.").
-define(SCD80511, "Taux Crit de Compétence +{0}%").
-define(SCD80521, "Pour chaque {0}% de PV perdus par la cible, gagne {1}% multiplicateur de DGT de Compétence.").
-define(SCD80531, "Pour chaque {0}% de PV perdus par la cible, gagne {1}% multiplicateur de DGT de Compétence.").
-define(SCD80541, "Pour chaque {0}% de PV perdus par la cible, gagne {1}% multiplicateur de DGT de Compétence.").
-define(SCD80551, "Lorsqu'il est utilisé sur un personnage ayant moins de 50% de PV, le lanceur de sorts gagne l'invincibilité pendant {0} sec.").
-define(SCN70601, "Le Printemps Arrive : Renforcé(e)").
-define(SCN70611, "Offensive de Vigne : Renforcé(e)").
-define(SCN70621, "Scie de Rotin : Renforcé(e)").
-define(SCN70631, "Fleurs Épanouies : Renforcé(e)").
-define(SCN70641, "Royaume de la Nature : Renforcé(e)").
-define(SCN70651, "Colère de la Terre : Renforcé(e)").
-define(SCN80601, "Le Printemps Arrive : Éveillé").
-define(SCN80611, "Offensive de Vigne : Éveillé").
-define(SCN80621, "Scie de Rotin : Éveillé").
-define(SCN80631, "Fleurs Épanouies : Éveillé").
-define(SCN80641, "Royaume de la Nature : Éveillé").
-define(SCN80651, "Colère de la Terre : Éveillé").
-define(SCD80601, "Soigne de {0} alliés pour des PV égaux à {1}% d'ATQ après une Transformation réussie.").
-define(SCD80611, "A {0}% de chances de dissiper {1} couche d'affaiblissement pour les alliés.").
-define(SCD80621, "Inflige un Délier (ATQ -{0}%) pendant {1} sec.").
-define(SCD80631, "Durée de Guérison +{0} sec").
-define(SCD80641, "Si la cible possède moins de {0}% PV, multiplicateur de soins +{1}%.").
-define(SCD80651, "Compétence inflige du poison (subis {0}% DGT par seconde) pendant {1} sec.").
-define(SCN30401, "Roi Tartare : Ascension effectuée").
-define(SCN30411, "Flèche Spectrale : Ascension effectuée").
-define(SCN30421, "Loup Tartare : Ascension effectuée").
-define(SCN30431, "Impact Effrayant : Ascension effectuée").
-define(SCN30441, "Enchevêtrement Fantôme : Ascension effectuée").
-define(SCN30451, "Banshee Espace : Ascension effectuée").
-define(SCN30501, "Seigneur de la Guerre : Ascension effectuée").
-define(SCN30511, "Compétence de Récolte : Ascension effectuée").
-define(SCN30521, "Attaque au Sabre : Ascension effectuée").
-define(SCN30531, "Raid Tranchant : Ascension effectuée").
-define(SCN30541, "Étranglement du Sabre : Ascension effectuée").
-define(SCN30551, "Exécution Finale : Ascension effectuée").
-define(SCN30601, "Le Printemps Arrive : Ascension effectuée").
-define(SCN30611, "Offensive de Vigne : Ascension effectuée").
-define(SCN30621, "Scie de Rotin : Ascension effectuée").
-define(SCN30631, "Fleurs Épanouies : Ascension effectuée").
-define(SCN30641, "Royaume de la Nature : Ascension effectuée").
-define(SCN30651, "Colère de la Terre : Ascension effectuée").
-define(SCD30401, "DGT de Base Infligés +{0}%").
-define(SCD30411, "DGT de Base Infligés +{0}%").
-define(SCD30421, "DGT de Base Infligés +{0}%").
-define(SCD30431, "DGT de Base Infligés +{0}%").
-define(SCD30441, "DGT de Base Infligés +{0}%").
-define(SCD30451, "DGT de Base Infligés +{0}%").
-define(SCD30501, "DGT de Base Infligés +{0}%").
-define(SCD30511, "DGT de Base Infligés +{0}%").
-define(SCD30521, "DGT de Base Infligés +{0}%").
-define(SCD30531, "DGT de Base Infligés +{0}%").
-define(SCD30541, "DGT de Base Infligés +{0}%").
-define(SCD30551, "DGT de Base Infligés +{0}%").
-define(SCD30601, "DGT de Base Infligés +{0}%").
-define(SCD30611, "DGT de Base Infligés +{0}%").
-define(SCD30621, "DGT de Base Infligés +{0}%").
-define(SCD30631, "DGT de Base Infligés +{0}%").
-define(SCD30641, "Soin de base +{0}%").
-define(SCD30651, "DGT de Base Infligés +{0}%").
-define(SCD70641, "Compétence Fixe Soin +{0}").
-define(SCN70701, "Déesse lunaire : Renforcé(e)").
-define(SCN70711, "Flèche Lunaire : Renforcé(e)").
-define(SCN70721, "Impact de la lame lunaire : Renforcé(e)").
-define(SCN70731, "Coup de Clair de Lune : Renforcé(e)").
-define(SCN70741, "Abri au Clair de Lune : Renforcé(e)").
-define(SCN70751, "Essence Lunaire : Renforcé(e)").
-define(SCN30701, "Déesse lunaire : Ascension effectuée").
-define(SCN30711, "Flèche Lunaire : Ascension effectuée").
-define(SCN30721, "Impact de la lame lunaire : Ascension effectuée").
-define(SCN30731, "Coup de Clair de Lune : Ascension effectuée").
-define(SCN30741, "Abri au Clair de Lune : Ascension effectuée").
-define(SCN30751, "Essence Lunaire : Ascension effectuée").
-define(SCN80701, "Déesse lunaire : Éveillé").
-define(SCN80711, "Flèche Lunaire : Éveillé").
-define(SCN80721, "Impact de la lame lunaire : Éveillé").
-define(SCN80731, "Coup de Clair de Lune : Éveillé").
-define(SCN80741, "Abri au Clair de Lune : Éveillé").
-define(SCN80751, "Essence Lunaire : Éveillé").
-define(SCD80701, "Accorde aux alliés {0}% ATQ pendant {1}s avec un Morph réussi.").
-define(SCD80711, "A {0}% de chance de Percer les cibles (DÉF -{1}%) pendant {2}s.").
-define(SCD80721, "La Compétence inflige un Brise-genou (VIT de Déplacement -{0}%) pendant {1}s.").
-define(SCD80731, "Durée de l'Étourdissement +{0}s.").
-define(SCD80741, "Absorption du DGT du bouclier augmentée à {0}%.").
-define(SCD80751, "Lorsque vous attaquez des ennemis étourdis, le modificateur de DGT de la compétence augmente de {0}%.").
-define(BCN4001, "").
-define(BCD4001, "").
-define(BCN4002, "").
-define(BCD4002, "").
-define(SCN64001, "").
-define(SCD64001, "").
-define(SCN64011, "").
-define(SCD64011, "").
-define(SCN64021, "").
-define(SCD64021, "").
-define(SCN64031, "").
-define(SCD64031, "").
-define(SCN64041, "").
-define(SCD64041, "").
-define(SCN64051, "").
-define(SCD64051, "").
-define(SCN64061, "").
-define(SCD64061, "").
-define(SCN64071, "").
-define(SCD64071, "").
-define(SCN64081, "").
-define(SCD64081, "").
-define(SCN64091, "").
-define(SCD64091, "").
-define(SN301001, "").
-define(SCD61051, "").
-define(SCD61061, "").
-define(SCD62081, "").
-define(SCD62091, "").
-define(SCD63081, "").
-define(SCD63091, "").
-define(SCD64101, "").
-define(SCD64111, "").
-define(SCN193091, "").
-define(SCD193091, "").
-define(SCN193101, "").
-define(SCD193101, "").
-define(SCN193111, "").
-define(SCD193111, "").
-define(BCD1042, "").
-define(BCD1052, "").
-define(BCD1062, "").
-define(SCD61032, "").
-define(SCD61041, "").
-define(BCD2032, "").
-define(BCD2042, "").
-define(SCD62031, "").
-define(SCD62051, "").
-define(SCD62072, "").
-define(SCD63041, "").
-define(SCD63051, "").
-define(BCD3042, "").
-define(BCD3052, "").
-define(SCD81101, "").
-define(SCN31201, "").
-define(SCN71201, "").
-define(SCN81201, "").
-define(SCD81201, "").
-define(SCN170441, "").
-define(SCD170441, "").
-define(SCN170451, "").
-define(SCD170451, "").
-define(SCN170461, "").
-define(SCD170461, "").
-define(SCN170471, "").
-define(SCD170471, "").
-endif.

